name: Compilando y Verificando
on: [push, pull_request]
jobs:
  jekyll:
    name: "Compilando y verificando Jekyll"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configurar Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-new-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-new-
      - name: Installar ruby gems
        run: |
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - name: Compilando Sitio con Jekyll
        run: |
          bundle exec jekyll build
      - name: Corriendo htmlproofer
        run: |
          bundle exec htmlproofer ./_site --assume-extension --check-html --disable-external --url-ignore "/#.*/"
      # - name: Ping FeaturePeek
      #   run: bash <(curl -s https://peek.run/ci)
